version = 0.1
[default.deploy.parameters]
stack_name = "cloud-resume"
resolve_s3 = true
s3_prefix = "cloud-resume"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
