name: Pull Request Workflow

on:
  push:
    branches:
      - 'actions'

jobs:
  cloudformation-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
	uses: actions/checkout@v3
      - name: Linter install
        uses: scottbrenner/cfn-lint-action@v2
	with:
	  command: cfn-lint -t ./main.yaml