name: Deploy Lambda Function

on:
  push:
    branches:
      - actions

jobs:
  deploy:
    name: Deploy Lambda Function
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build  # If you have a build step for your Lambda function

      - name: Package Lambda function
        run: zip -r lambda.zip .  # Package your Lambda function code

      - name: Upload ZIP file to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: resume-lambda-bucket-01
          AWS_REGION: us-east-1
          SOURCE_DIR: ./lambda.zip
          DEST_DIR: /

          # AWS credentials
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}