name: Cloudformation

on:
  push:
    branches: [ actions ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Install Zip Tool
        uses: montudor/action-zip@v1

      - name: Create artifact/publish directory if not exists
        run: mkdir -p ./artifact/publish

      - name: Copy lambda code to artifact directory
        run: cp ./backend/test.py ./artifact/publish

      - name: Create zip file for lambda
        run: zip -qq -r lambda.zip .
        working-directory: artifact/publish

      - uses: actions/upload-artifact@v3
        with:
          name: lambda
          path: ./artifact

      - name: Copy Cloudformation Template
        run: cp ./templates/deployment.yaml ./artifact/deployment.yaml

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Upload to S3
        run: aws s3 cp ./artifact/lambda.zip s3://resume-lambda-bucket-01