name: resume-deployment

on:
  push:
    branches: [ actions ]

jobs:
  build-infra:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: sam build
        working-directory: sam-formation
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
        working-directory: sam-formation
      
      # - name: Upload to S3
      #   run: aws s3 cp ./artifact/lambda.zip s3://resume-lambda-bucket-01
      # - name: test get-function
      #   run: cd resume-challenge/get-function && go test -v ./ && ../../
      # - name: test put-function
      #   run: cd resume-challenge/put-function && go test -v ./ && ../../